# Κάνοντας compile το <foo>_test.c με μια υλοποίηση <foo>.c του
# συγκεκριμένου τύπου, παράγουμε ένα tets για την υλοποίηση αυτή.


# Υλοποιήσεις μέσω ADT Set: ADTPriorityQueue
# Χρειαζόμαστε και υλοποιήσεις για τα ADTSet και ADTVector
#
UsingADTSet_ADTPriorityQueue_test_OBJS = ADTPriorityQueue_test.o $(MODULES)/UsingADTSet/ADTPriorityQueue.o $(MODULES)/UsingAVL/ADTSet.o $(MODULES)/UsingDynamicArray/ADTVector.o


# Ο βασικός κορμός του Makefile
include ../common.mk